BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Hour" (
	"ID"	INTEGER UNIQUE,
	"Value"	NUMERIC NOT NULL,
	"Variety"	REAL NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tax" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"affects"	INTEGER NOT NULL,
	"percentile"	REAL NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("affects") REFERENCES "Hour"("ID")
);
CREATE TABLE IF NOT EXISTS "Day" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"dayMonth"	TEXT NOT NULL,
	"count"	INTEGER NOT NULL,
	"dayTotal"	REAL NOT NULL,
	"dayTotalAfterTax"	REAL NOT NULL,
	"hourVariety"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("hourVariety") REFERENCES "Hour"("ID")
);
INSERT INTO "Hour" VALUES (1,5,'normal');
COMMIT;
